language: python
python:
- 2.7
- 3.5
- pypy
env:
- DJANGO_SETTINGS_ENVIRONMENT=test
install:
- pip install -U pip
- pip install django-constance[database]
script: ./manage.py test --noinput
sudo: false
deploy:
  provider: pypi
  user: nzme
  password:
    secure: todo
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: NZME/django-constance-cli
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
